[package]
name = "shrinkage"
version = "0.2.0"
edition = "2024"
rust-version = "1.89"
description = "Composable regularized statistical models in Rust."
authors = ["Johan Larsson <johan@jolars.co>"]
license = "MIT"
repository = "https://github.com/jolars/shrinkage"
readme = "README.md"
keywords = ["statistics", "optimization", "regression", "regularization"]
categories = ["mathematics", "science"]

[dependencies]
lazymatrix = { version = "=0.3.0", default-features = false }
faer = { version = "0.24", optional = true, default-features = false, features = [
  "std",
  "linalg",
] }

[features]
default = []
faer = ["faer_v0_24"]
faer_v0_24 = ["dep:faer", "lazymatrix/faer_v0_24"]
nalgebra = ["nalgebra_v0_34"]
nalgebra_v0_34 = ["lazymatrix/nalgebra_v0_34"]
ndarray = ["ndarray_v0_17"]
ndarray_v0_17 = ["lazymatrix/ndarray_v0_17"]
sprs = ["sprs_v0_11"]
sprs_v0_11 = ["lazymatrix/sprs_v0_11"]

[dev-dependencies]
criterion = { version = "0.8.2", default-features = false }
nalgebra = { version = "0.34", default-features = false, features = ["std"] }
nalgebra-sparse = "0.11"
ndarray = { version = "0.17.2", default-features = false, features = ["std"] }
sprs = { version = "0.11.4", default-features = false }

[[example]]
name = "normalization"
required-features = ["faer_v0_24"]

[[example]]
name = "lasso"
required-features = ["faer_v0_24"]

[[bench]]
name = "lasso"
harness = false
required-features = ["faer_v0_24"]

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
