# /// script
# requires-python = ">=3.13"
# dependencies = ["scikit-learn==1.9.1"]
# ///
"""Regenerate with `uv run --script generate_lasso_sklearn.py > lasso_sklearn.csv`.

scikit-learn's Lasso uses ||y - Xb - a||^2 / (2n) + alpha * ||b||_1.
This script transforms X explicitly because Shrinkage normalizes lazily and
penalizes coefficients on the transformed scale.

On NixOS, uv's binary wheels may need LD_LIBRARY_PATH to include the lib
directories of `nixpkgs#stdenv.cc.cc.lib` and `nixpkgs#zlib`.
"""

import csv
import sys

import numpy as np
import sklearn
from sklearn.linear_model import Lasso


X = np.array(
    [
        [0, 1, 3, 0],
        [1, 0, 3, 2],
        [2, 2, 3, 0],
        [3, -1, 3, 1],
        [4, 3, 3, 0],
        [5, 1, 3, 2],
        [6, 4, 3, 1],
        [7, -2, 3, 0],
    ],
    dtype=float,
)
Y = np.array([1, 2.3, 0.8, 3.9, 4.2, 2.7, 6.1, 5.4])
PREDICT_X = np.array([[1.5, -0.5, 3, 1], [8, 2, 3, 0]])
CASES = [
    ("raw_intercept", "none", True, 0.12),
    ("raw_no_intercept", "none", False, 0.12),
    ("auto_intercept", "auto", True, 0.12),
    ("auto_no_intercept", "auto", False, 0.12),
    ("auto_stronger_penalty", "auto", True, 0.45),
    ("raw_null_model", "none", True, 100.0),
]


def main():
    writer = csv.writer(sys.stdout, lineterminator="\n")
    writer.writerow(
        [
            f"# Generated by scikit-learn {sklearn.__version__}; "
            "run uv run --script generate_lasso_sklearn.py > lasso_sklearn.csv"
        ]
    )
    writer.writerow(
        ["case", "normalization", "fit_intercept", "alpha", "intercept"]
        + [f"coefficient_{j}" for j in range(X.shape[1])]
        + ["objective", "prediction_0", "prediction_1"]
    )
    for name, normalization, fit_intercept, alpha in CASES:
        if normalization == "auto":
            centers = X.mean(axis=0) if fit_intercept else np.zeros(X.shape[1])
            scales = X.std(axis=0, ddof=0)
            scales[scales == 0] = 1
        else:
            centers = np.zeros(X.shape[1])
            scales = np.ones(X.shape[1])
        transformed = (X - centers) / scales
        model = Lasso(
            alpha=alpha,
            fit_intercept=fit_intercept,
            tol=1e-13,
            max_iter=1_000_000,
            selection="cyclic",
        ).fit(transformed, Y)
        if model.dual_gap_ > 1e-10:
            raise RuntimeError(f"{name} did not converge: dual gap {model.dual_gap_}")
        coefficients = model.coef_ / scales
        intercept = float(model.intercept_ - coefficients @ centers)
        predictions = PREDICT_X @ coefficients + intercept
        residual = Y - (X @ coefficients + intercept)
        objective = residual @ residual / (2 * len(Y)) + alpha * np.abs(model.coef_).sum()
        writer.writerow(
            [name, normalization, int(fit_intercept), alpha, intercept]
            + coefficients.tolist()
            + [objective]
            + predictions.tolist()
        )


if __name__ == "__main__":
    main()
